### ISSUE TITLE
Ignored groups not working

### ISSUE THREAD

**Issue by maszaa** [tillkruss/redis-cache#164]
I'm trying to ignore a group `WPML_TM_ICL_Translations--translations`. The plugin diagnostics show that it has recognized this:

> Ignored Groups: [
>     "counts",
>     "plugins",
>     "WPML_TM_ICL_Translations--translations",
> ]

But still entries with this group keep on getting stored to Redis. I've disabled and enabled the plugin, flushed the cache, restarted php-fpm, but nothing helps. After flushing the cache the Redis doesn't have keys including this group but when I open some page those keys appear again. It's also strange that wp cli's cache command can't find any entries with this group.

Am I doing something wrong? I need to get this group ignored as WPML just keeps populating my cache with it's huge objects and causes memory allocation problems.

I'm using version 1.5.7 of Redis cache. Has there been any fixes related to ignored groups since that?

**Comment by maszaa** [comment]
They key seems to be `WPML_TM_ICL_Translations::translations` with WP..., damn. That did it.

**Comment by naxvog** [comment]
Quick explanation on why this key is transformed by the plugin:
In order to preserve key group association keys need to be transformed before being sent to redis - as there is no support for groups just simple string keys in redis.
There has to be a separating character to implement such functionality. In this case `:` was chosen to do that. In order to avoid key placement in wrong groups or misuse to do exactly that, this character has to be replaced by an other character - in this case: `-`.

However we could do the transformation for every group defined in the ignored groups as well to avoid confusion.

**Comment by tillkruss** [comment]
That’s a great idea.

**Comment by maszaa** [comment]
What if group or key originally has `-` character(s)?

**Comment by naxvog** [comment]
Nothing happens to the `-`characters. So it is possible to have a group collision if you define a group that mimics the sanitized version of a group that is being sanitized later in the code.
e.g. `WPML_TM_ICL_Translations--translations` and `WPML_TM_ICL_Translations::translations`
